# Generated by Django 4.2.1 on 2023-06-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coursepage_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmca',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='Media/mca_img'),
        ),
    ]
