# Generated by Django 4.2.1 on 2023-07-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_categoriesmca_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='categoriesmca',
            name='pages',
            field=models.URLField(null=True),
        ),
    ]
