# Generated by Django 4.2.1 on 2023-07-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_course_category_alter_categoriesmca_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmca',
            name='pages',
        ),
        migrations.AddField(
            model_name='categoriesmca',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null='Ture', on_delete=django.db.models.deletion.CASCADE, to='app.categoriesmca'),
            preserve_default='Ture',
        ),
    ]
