# Generated by Django 4.2.1 on 2023-07-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_categoriesmca_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='category',
            field=models.ForeignKey(null='Ture', on_delete=django.db.models.deletion.CASCADE, to='app.categoriesmca'),
            preserve_default='Ture',
        ),
    ]
