# Generated by Django 4.2.1 on 2023-07-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_coursepage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='featured_image',
            field=models.FileField(null=True, upload_to='templates\\main'),
        ),
    ]
