# Generated by Django 4.2.1 on 2023-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_categories_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='categoriesmca',
            name='dicription',
            field=models.TextField(default='helo'),
        ),
    ]
