# Generated by Django 4.2.1 on 2023-07-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_categories_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmca',
            name='dicription',
        ),
    ]
